#
# travis-ci integration for native-file-tests
#

notifications:
  email: false

language: c

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi
script: scons
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export NFT_PLATFORM_NAME="macos"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NFT_PLATFORM_NAME="linux"; fi
  - ./dist.sh $NFT_PLATFORM_NAME v0.1.3

deploy:
  provider: releases
  api_key:
    secure: "Dpw6aKsvDeeQTDD5wwKYDOt5WcFdgla6aglJXk/IIDtam8lX3ZKUJA/Pk6rOUyA6AyhO4TJcODt37WTKQDe+o832Yyw4SVp0UFDRcxd6ErybzEkHkRBrhJWq0cJmSkHv9GmlGrno8NgjhplbHGsWA7C7sMkCh2WAB2zJRomdXgY="
  file: ''
  skip_cleanup: true
  on:
    repo: udidb/native-file-tests
    tags: true

jobs:
  include:
    - stage: deploy-all
      script:
        - if [ -z "$TRAVIS_TAG" ]; then echo "Skipping deploy"; else echo ./dist-all.sh "$TRAVIS_TAG"; fi
      deploy:
        provider: releases
        api_key:
          secure: "Dpw6aKsvDeeQTDD5wwKYDOt5WcFdgla6aglJXk/IIDtam8lX3ZKUJA/Pk6rOUyA6AyhO4TJcODt37WTKQDe+o832Yyw4SVp0UFDRcxd6ErybzEkHkRBrhJWq0cJmSkHv9GmlGrno8NgjhplbHGsWA7C7sMkCh2WAB2zJRomdXgY="
        file: ''
        skip_cleanup: true
        on:
          repo: udidb/native-file-tests
          tags: true
