#
# travis-ci integration for native-file-tests
#

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi

language: c

script: scons

notifications:
  email: false
