#
# appveyor configuration for native-file-tests
#

image:
- Visual Studio 2017

environment:
  global:
    RUST_VERSION: 1.25.0
  matrix:
    - TARGET: x86_64-pc-windows-msvc

version: '0.1.0.{build}'

install:
  - %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - python --version
  - pip --version
  - pip install pypiwin32
  - pip install wheel
  - pip install scons==3.0.1
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - where cl
  - cl /?

build: false

test_script:
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - ps: >-
      If ( $Env:APPVEYOR_REPO_TAG -eq 'true' ) {
        $Env:TAG = $Env:APPVEYOR_REPO_TAG_NAME
      } else {
        $Env:TAG = 'snapshot'
      }
  - scons configure MSVC_VERSION=14.1
  - scons
  - python dist.py windows $TAG
  - ps: $Env:NFT_DIR = "$pwd\\native-file-tests-windows-$Env:TAG"
  - cd rust-binding
  - cargo build && cargo test
  - cd ..\java-binding
  - mvn clean verifiy -Dnative.file.tests.basePath=$Env:NFT_DIR

cache:
  - C:\Users\appveyor\.cargo\registry
  - rust-binding\target

deploy:
  artifact: native-file-tests-windows-*.zip
  auth_token:
    secure: UvBnHAlUB3CKn3xPKG9z1+ZghBNXXsJqkHvA094ma8XyCMJWdYFQS67419we6XaD
  on:
    appveyor_repo_tag: true
  provider: GitHub

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
