[package]
name = "native_file_tests"
version = "0.1.0"
authors = ["Dan McNulty <dkmcnulty@gmail.com>"]

[dependencies]
goblin = "0.0.14"
serde =  "1.0"
serde_derive = "1.0"
serde_json = "1.0"
pdb = { git = "https://github.com/mcnulty/pdb.git", branch = "procedure-symbol" }
